### ISSUE TITLE
user should be able to change head color

### ISSUE THREAD

**Issue by fingerpich** [fingerpich/jalali-angular-datepicker#15]

**Comment by fingerpich** [comment]
you could change head style using css code

```css
/deep/ dp-date-picker {
       .dp-calendar-nav-container{
                  background: #464646 !important;
                  color: #ffffff;
       }
}
```
