### ISSUE TITLE
problem while use it in angular material expansion panel 

### ISSUE THREAD

**Issue by alimashal** [fingerpich/jalali-angular-datepicker#37]
I used it with angular material everything is fine except with angular expansion panel.
angular expansion panel has greater z-index and hide the date picker I tried lots of way no one working any help

**Comment by fingerpich** [comment]
Hi,

Why don't you change it using something like the following css code?
```css
/deep/ dp-date-picker .dp-popup{
   z-index: 10000000000000000000000000000;
}
```
